import json

def generate_workshop_bbcode(json_file="window_court_check.json"):
    try:
        with open(json_file, 'r') as f:
            results = json.load(f)
    except FileNotFoundError:
        print(f"Error: {json_file} not found. Run the check script first.")
        return
    except json.JSONDecodeError:
        print(f"Error: {json_file} contains invalid JSON.")
        return

    bbcode_output = []
    bbcode_output.append("Court UI Compatibility Status:\n")
    
    for mod_id, mod_data in results.items():
        status = "compatible" if mod_data['exists'] else "incompatible"
        color = "brightgreen" if mod_data['exists'] else "red"
        name = mod_data.get('short') or mod_data.get('name') or f"ID {mod_id}"
        
        badge_url = (
            f"https://img.shields.io/badge/{name.replace(' ', '%20')}-"
            f"{status}-{color}?style=plastic"
        )
        
        workshop_url = f"https://steamcommunity.com/sharedfiles/filedetails/?id={mod_id}"
        
        bbcode = (
            f"[URL={workshop_url}][IMG]{badge_url}[/IMG][/URL]"
        )
        bbcode_output.append(bbcode)
    
    # Add a separator line
    bbcode_output.append("\nGenerated by automated compatibility check")
    
    # Print to console and copy to clipboard if possible
    final_output = "\n".join(bbcode_output)
    print("\nCopy this BBCode to your Steam Workshop description:\n")
    print(final_output)
    
    try:
        import pyperclip
        pyperclip.copy(final_output)
        print("\n(BBCode has been copied to your clipboard)")
    except ImportError:
        print("\nTip: Install pyperclip (pip install pyperclip) to auto-copy to clipboard")

if __name__ == "__main__":
    generate_workshop_bbcode()